/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=deploy/cobalt-cloudflare/wrangler.jsonc --include-runtime=false deploy/cobalt-cloudflare/worker-configuration.d.ts` (hash: 8b5e7bda5cc8dbb1857701debc0b6aec)
interface __BaseEnv_Env {
	COBALT_PUBLIC_URL: "https://cobalt.sublime.kiwi/";
	COBALT_API_KEY: string;
	COBALT: DurableObjectNamespace<import("./src/index").CobaltContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CobaltContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "COBALT_PUBLIC_URL" | "COBALT_API_KEY">> {}
}
